% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  spanish,
  a4paper,
  oneside]{scrbook}
\usepackage{xcolor}
\usepackage[top=25mm,bottom=25mm,left=30mm,right=20mm]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother


% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\ifLuaTeX
\usepackage[bidi=basic]{babel}
\else
\usepackage[bidi=default]{babel}
\fi
% get rid of language-specific shorthands (see #6817):
\let\LanguageShortHands\languageshorthands
\def\languageshorthands#1{}


\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\AtBeginDocument{\hypersetup{linkcolor=black}}
% ---------- Paquetes tipograficos y microajustes ----------
\usepackage{microtype}        % mejor interletrado y justificado
\usepackage{csquotes}         % comillas tipograficas
\usepackage{iftex}
\ifPDFTeX\else
  % Seleccion de fuentes solo cuando XeTeX/LuaTeX esta disponible.
  \IfFontExistsTF{TeX Gyre Termes}{
    \setmainfont{TeX Gyre Termes}
  }{
    \IfFontExistsTF{Latin Modern Roman}{\setmainfont{Latin Modern Roman}}{}
  }
  \IfFontExistsTF{TeX Gyre Heros}{
    \setsansfont{TeX Gyre Heros}
  }{
    \IfFontExistsTF{Latin Modern Sans}{\setsansfont{Latin Modern Sans}}{}
  }
  \IfFontExistsTF{TeX Gyre Cursor}{
    \setmonofont{TeX Gyre Cursor}
  }{
    \IfFontExistsTF{Latin Modern Mono}{\setmonofont{Latin Modern Mono}}{}
  }
\fi
\usepackage{enumitem}         % listas compactas
\setlist{itemsep=.2em, topsep=.2em}

% ---------- KOMA-Script: estilo de titulos y espaciado ----------
\KOMAoptions{
  headings=big,
  parskip=half,
  fontsize=12pt,
  appendixprefix=true
}
\setlength{\parindent}{1.5em}
\setlength{\parskip}{0.6em}
\usepackage{indentfirst}
\usepackage{setspace}         % Control del interlineado del documento
\setstretch{1.5}

% ---------- Encabezados y pies (scrlayer-scrpage) ----------
\usepackage[automark,headsepline]{scrlayer-scrpage}
\clearpairofpagestyles
\automark[chapter]{chapter}
\ihead{\pagemark}
\ohead{\itshape\headmark}
\setheadsepline{0.4pt}
\renewcommand*{\chaptermarkformat}{}
\renewcommand*{\chapterpagestyle}{scrheadings}
\pagestyle{scrheadings}
\makeatletter
\let\ps@plain\ps@scrheadings
\makeatother
\cfoot{}

% ---------- Hipervinculos mas sobrios ----------
\usepackage{hyperref}
\hypersetup{
  colorlinks=true,
  linkcolor=black,
  citecolor=[rgb]{0.05,0.2,0.5},
  urlcolor=[rgb]{0.05,0.2,0.5},
  pdfauthor={\@author},
  pdftitle={\@title}
}

% ---------- Leyendas de figuras/tablas ----------
\usepackage[labelfont=bf,textfont=it]{caption}
\captionsetup{
  skip=8pt
}

% ---------- Ubicacion de figuras y tablas ----------
% Por defecto, los flotantes se colocan lo mas cerca posible de su posicion
% en el texto (!ht = "aqui o arriba, ignorando restricciones esteticas").
% Para que un flotante concreto vuelva a moverse libremente, usa en su bloque
% #| fig-pos: "tbp"  (o #| tbl-pos: "tbp"); para anclarlo de forma rigida,
% usa #| fig-pos: "H".
\usepackage{float}
\makeatletter
\def\fps@figure{!ht}
\def\fps@table{!ht}
\makeatother

% ---------- Tabla de contenidos ----------
\KOMAoptions{toc=graduated}
\RedeclareSectionCommand[tocnumwidth=3em]{chapter}
\RedeclareSectionCommand[tocindent=3.25em,tocnumwidth=2.8em]{section}
\RedeclareSectionCommand[tocindent=6.5em,tocnumwidth=2.5em]{subsection}
\makeatletter
\newcommand*{\tocdotfill}{\leavevmode\leaders\hbox to .6em{\hss.\hss}\hfill}
\makeatother
\RedeclareSectionCommand[toclinefill=\tocdotfill]{chapter}
\RedeclareSectionCommand[toclinefill=\tocdotfill]{section}
\RedeclareSectionCommand[toclinefill=\tocdotfill]{subsection}
\renewcommand*{\contentsname}{Tabla de contenido}
\setkomafont{chapterentry}{\normalfont}
\setkomafont{chapterentrypagenumber}{\normalfont}

% ---------- Viudas/Huerfanas y cortes de pagina ----------
\clubpenalty=10000
\widowpenalty=10000
\displaywidowpenalty=10000

% ---------- Entorno abstract para scrbook ----------
\providecommand{\abstractname}{Resumen}
\makeatletter
\@ifundefined{abstract}{
  \newenvironment{abstract}{
    \cleardoublepage
    \thispagestyle{plain}
    \null\vfill
    \begin{center}
      {\bfseries\Large \abstractname\par}
    \end{center}\vspace{1em}
    \begingroup
  }{
    \par\endgroup
    \vfill\null
    \cleardoublepage
  }
}{}
\makeatother

% ---------- Soporte de subtitulo desde YAML ----------
\makeatletter
\providecommand{\subtitle}[1]{\gdef\@subtitle{#1}}
\providecommand{\@subtitle}{}
\makeatother

\makeatletter
\newcommand{\facso@iflist}[4]{%
  \begingroup
    \def\addvspace##1{}%
    \def\numberline##1{##1}%
    \def\facso@target{#2}%
    \newcount\facso@entrycount
    \facso@entrycount=0\relax
    \long\def\contentsline##1##2##3{%
      \def\facso@this{##1}%
      \ifx\facso@this\facso@target
        \advance\facso@entrycount\@ne
      \fi
    }%
    \InputIfFileExists{\jobname.#1}{}{}%
  \endgroup
  \ifnum\facso@entrycount>0\relax
    #3%
  \else
    #4%
  \fi}
\renewcommand{\listoffigures}{%
  \facso@iflist{lof}{figure}{%
    \cleardoublepage
    \phantomsection
    \addchap*{Listado de Figuras}%
    \thispagestyle{scrheadings}%
    \markboth{Listado de Figuras}{Listado de Figuras}%
    \addcontentsline{toc}{chapter}{Listado de Figuras}%
    \@starttoc{lof}%
    \cleardoublepage
    \automark[chapter]{chapter}%
  }{}}
\renewcommand{\listoftables}{%
  \facso@iflist{lot}{table}{%
    \cleardoublepage
    \phantomsection
    \addchap*{Listado de Tablas}%
    \thispagestyle{scrheadings}%
    \markboth{Listado de Tablas}{Listado de Tablas}%
    \addcontentsline{toc}{chapter}{Listado de Tablas}%
    \@starttoc{lot}%
    \cleardoublepage
    \automark[chapter]{chapter}%
  }{}}
\makeatother

% --- Desactivar portada y abstract automaticos de Pandoc (PDF) ---
\AtBeginDocument{\let\maketitle\relax}
\renewenvironment{abstract}{}{}
\providecommand{\appendixname}{}
\providecommand{\appendixtocname}{}
\providecommand{\appendixpagename}{}
\renewcommand*{\appendixname}{Anexo}
\renewcommand*{\appendixtocname}{Anexos}
\renewcommand*{\appendixpagename}{Anexos}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[skins,breakable]{tcolorbox}}
\@ifpackageloaded{fontawesome5}{}{\usepackage{fontawesome5}}
\definecolor{quarto-callout-color}{HTML}{909090}
\definecolor{quarto-callout-note-color}{HTML}{0758E5}
\definecolor{quarto-callout-important-color}{HTML}{CC1914}
\definecolor{quarto-callout-warning-color}{HTML}{EB9113}
\definecolor{quarto-callout-tip-color}{HTML}{00A047}
\definecolor{quarto-callout-caution-color}{HTML}{FC5300}
\definecolor{quarto-callout-color-frame}{HTML}{acacac}
\definecolor{quarto-callout-note-color-frame}{HTML}{4582ec}
\definecolor{quarto-callout-important-color-frame}{HTML}{d9534f}
\definecolor{quarto-callout-warning-color-frame}{HTML}{f0ad4e}
\definecolor{quarto-callout-tip-color-frame}{HTML}{02b875}
\definecolor{quarto-callout-caution-color-frame}{HTML}{fd7e14}
\makeatother
\makeatletter
\@ifpackageloaded{bookmark}{}{\usepackage{bookmark}}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Tabla de contenidos}
\else
  \newcommand\contentsname{Tabla de contenidos}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{Listado de Figuras}
\else
  \newcommand\listfigurename{Listado de Figuras}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{Listado de Tablas}
\else
  \newcommand\listtablename{Listado de Tablas}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figura}
\else
  \newcommand\figurename{Figura}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Tabla}
\else
  \newcommand\tablename{Tabla}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listado}
\newcommand*\listoflistings{\listof{codelisting}{Listado de Listados}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Publicaciones Académicos y Académicas FACSO},
  pdfauthor={Gabriel Cortés},
  pdflang={es},
  colorlinks=true,
  linkcolor={Maroon},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Publicaciones Académicos y Académicas FACSO}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{2020-2025}
\author{Gabriel Cortés}
\date{13 de julio de 2026}
\begin{document}
\frontmatter
\maketitle

% --- title-pdf.tex personalizado para portada formal ---
\makeatletter
\providecommand{\subtitle}[1]{\gdef\@subtitle{#1}}
\providecommand{\@subtitle}{}
\providecommand{\frontmattercontext}{}
\providecommand{\advisorname}{}
\providecommand{\advisorlabel}{Profesor guia:}
\providecommand{\frontmatterlocation}{}
\InputIfFileExists{includes/cover-config.tex}{}{}

\newcommand{\PrintTitle}{%
  {\sffamily\bfseries\fontsize{24pt}{28pt}\selectfont \@title\par}%
}
\newcommand{\PrintSubtitle}{%
  \begingroup
  \edef\temp{\detokenize{\@subtitle}}%
  \ifx\temp\empty\relax
    % sin subtitulo
  \else
    {\sffamily\bfseries\large \@subtitle\par}%
  \fi
  \endgroup
}
\newcommand{\PrintAuthor}{%
  {\Large\bfseries \@author\par}%
}
\newcommand{\PrintDate}{%
  {\small \@date\par}%
}
\makeatother

\begin{titlepage}
\thispagestyle{empty}
\begin{center}
\vspace*{10mm}

% Logo o imagen institucional
\includegraphics[width=0.35\textwidth]{assets/cover.png}\par
\vspace{12mm}

% Titulo y subtitulo
\PrintTitle
\vspace{6mm}
\PrintSubtitle

\vspace{22mm}
\begingroup
\edef\temp{\detokenize{\frontmattercontext}}%
\ifx\temp\empty\relax
  % sin contexto adicional
\else
  {\normalsize \frontmattercontext\par}
\fi
\endgroup

\vspace{18mm}
\PrintAuthor

\vspace{16mm}
\begingroup
\edef\temp{\detokenize{\advisorname}}%
\ifx\temp\empty\relax
  % sin tutor
\else
  \rule{0.45\textwidth}{0.4pt}\par
  {\small \advisorlabel\ \advisorname\par}
\fi
\endgroup

\vfill
\begingroup
\edef\temp{\detokenize{\frontmatterlocation}}%
\ifx\temp\empty\relax
  % sin ubicacion
\else
  {\small \frontmatterlocation\par}
\fi
\endgroup
\PrintDate

\end{center}
\end{titlepage}

% Preliminares (numeros romanos) y estilo simple
\frontmatter
\pagestyle{scrheadings}

\setcounter{tocdepth}{2} % (o 1/3 segun prefieras)
\tableofcontents
\listoffigures
\listoftables


\mainmatter
\bookmarksetup{startatroot}

\chapter*{Resumen ejecutivo}\label{resumen-ejecutivo}
\addcontentsline{toc}{chapter}{Resumen ejecutivo}

\markboth{Resumen ejecutivo}{Resumen ejecutivo}

\begin{tcolorbox}[enhanced jigsaw, left=2mm, bottomrule=.15mm, colframe=quarto-callout-note-color-frame, toprule=.15mm, leftrule=.75mm, arc=.35mm, breakable, rightrule=.15mm, opacityback=0, colback=white]
\begin{minipage}[t]{5.5mm}
\textcolor{quarto-callout-note-color}{\faInfo}
\end{minipage}%
\begin{minipage}[t]{\textwidth - 5.5mm}

\textbf{Período de referencia:} 2020-2025 · Síntesis elaborada a partir
de los capítulos de Metodología y Resultados del informe
\emph{Publicaciones Académicos y Académicas FACSO}.

\end{minipage}%
\end{tcolorbox}

\section{Propósito y alcance}\label{propuxf3sito-y-alcance}

Este estudio corresponde a un análisis cuantitativo descriptivo que
caracteriza el volumen, la composición y el impacto de la producción
científica de la Facultad de Ciencias Sociales de la Univerisdad de
Chile. El período de referencia corresponde a 2020-2025, con un universo
de \textbf{1.162 publicaciones únicas} identificadas.

\section{Metodología}\label{metodologuxeda}

\textbf{Datos}

La construcción de la base combinó múltiples fuentes:

\begin{itemize}
\tightlist
\item
  \textbf{Fuente principal:} el mantenedor de publicaciones de
  \textbf{SEPA-VID}, filtrando las publicaciones adscritas a FACSO entre
  2020 y 2025. Esta fuente contiene mayoritariamente artículos indexados
  en WoS, Scopus y Scielo, y solo registra publicaciones producidas
  durante la vigencia del nombramiento de cada académico.
\item
  \textbf{API de ORCID} aplicada a 72 investigadores del Colaboratorio
  de de Investigación en Ciencias Sociales. Se utilizó para recuperar
  libros, capítulos e indexaciones ausentes en la base de la SEPA-VID.
\item
  Bases como la WoS Master List, la Scopus Source title list y la API de
  Scielo permitieron \textbf{enriquecer la base de datos}, identificando
  la indexación, idioma y acceso abierto. De la \textbf{API de Scopus}
  se extrajo el número de citas por publicación. El \textbf{SCImago
  Journal Rank} (SJR) entregó los cuartiles e indicadores del impacto de
  las revistas.
\end{itemize}

La caracterización del cuerpo académico se basó en la base de personal
de la Facultad, considerando todos los nombramientos vigentes al 31 de
dicimebre del 2025, exclyendo a investigadores postdoctorales.

\textbf{Variables}

Se incluyeron en el análisis artículos de revistas académicas, capítulos
de libros y libros. Paa los análisis agregados a nivel de la Facultad,
la unidad de análisis fue las publicaciones únicas (n=1.162). En tanto,
para la caracterización según género, edad y jerarquía, la unidad fue
cada par distinto de publicaicón autor (n=1.328). La mayoría de los
análisis se ponderaron por Jornadas Completas Equivalente (JCE),
calculadas como la suma de horas reales de dedicación académicas
dividida por una jornada completa (44 horas).

\section{Principales Hallazgos}\label{principales-hallazgos}

\subsection{Volúmen y composición}\label{voluxfamen-y-composiciuxf3n}

La producción total del período analizado fue de 1.162 publicaciones
únicas, con un claro predominio de los artículos de revista (946, o un
81\%), seguidos de 171 capítulos de libro (15\%) y 45 libros (4\%). La
productividad total alcanzó las 7,8 publicaciones por JCE en 5 años.
Tras un incremento sustancial entre 2020 y 2021, posiblemente atribuile
a un efecto de rebote posterior a la pandemia, el volúmen se mantuvo con
relativa estabilidad entre 2022 y 2025 (ver
Figura~\ref{fig-publicacion-anio})

\subsection{Concentración de la
productividad}\label{concentraciuxf3n-de-la-productividad}

Se detectó una alta dispersión en la producción académica en la
Facultad. La media de publicaciones en el período es de 3 publicaciones
por académico, mientras que el 20\% más productivo concentra dos tercios
de las publicaciones. Es más, la mitad de la producción total
corresponde a cerca del 13\% del cuerpo académico, es decir, a los 25
académicos más productivos de la Facultad (ver
Figura~\ref{fig-publicacion-lorenz})

\subsection{Perfiles de los autores}\label{perfiles-de-los-autores}

El análisis desagrado revela diferencias sistemáticas según las
características de los autores:

\textbf{Departamento}: Destaca el Departamento de Trabajo Social con el
mayor volumen de publicaciones por Jornadas Completas Equivalente, con
13,9 (Figura~\ref{fig-publicacion-depto}). Por otro lado, el
Departamento de Antropología lidera en la proporción de publicaciones en
cuartiles altos de impacto.

\textbf{Género}: Las académicas son sistemáticamente más productivas que
sus pares masculinos (10,73 frente 7,19 publicaciones por JCE, ver
Figura~\ref{fig-publicacion-genero}). Esta brecha se observa también
cantidad de citas, índice h y en la proporción de publicaciones en
cuartiles altos.

\textbf{Edad}: La mayor productividad se concentra en el tramo de entre
50 a 59 años (10,58 por JCE), con una caída abrupta en el grupo de más
de 60 años (ver Figura~\ref{fig-publicacion-edad}). Estas diferencias se
replican en los indicadores de impacto académico.

\textbf{Jerarquía}: Existe una brecha importante entre la Jerarquía de
Asistente (4,49 por JCE) y la de Asociado. La brecha entre Asociados y
Titulares es menor, variando según el indicador. Los asociados publican
más por JCE (Figura~\ref{fig-publicacion-jerarquia}) y suman mayor
número de citas. sin embargo, los titulares los superan en canitdad de
publicaciones en WoS (Figura~\ref{fig-index-carac-3}) y en revistas Q1 o
Q2 (Figura~\ref{fig-sjr-depto})

\subsection{Impacto Académico}\label{impacto-acaduxe9mico}

El 78\% de los artículos se publica en revistas indexadas en WoS (42\%)
o Scopus (36\%), lo que probablemente refleja los criterios de
evaluación de los fondos concursables de ANID (ver
Figura~\ref{fig-index}). Por otro lado, el 67\% de las publicaciones con
SJR registrado se ubica en revistas Q1 o Q2. Las publicaciones en
revistas Q1 por sí solas llegan a un 42\% (Tabla~\ref{tbl-sjr})

Por otro lado, se contabilizaron 4.854 citas en el período, con un
promedio de 6,7 citas por artículo y un índice h institucional de 30. La
distribución de citas presenta una alta dispersión, con un rango que va
de 0 a 307 citas (Figura~\ref{fig-citas-densidad}). El Departamento de
Psicología registra el mayor número absoluto de citas entre los
departamentos de la Facultad (Tabla~\ref{tbl-citas-depto})

\begin{tcolorbox}[enhanced jigsaw, left=2mm, bottomrule=.15mm, colframe=quarto-callout-note-color-frame, toprule=.15mm, leftrule=.75mm, arc=.35mm, breakable, rightrule=.15mm, opacityback=0, colback=white]
\begin{minipage}[t]{5.5mm}
\textcolor{quarto-callout-note-color}{\faInfo}
\end{minipage}%
\begin{minipage}[t]{\textwidth - 5.5mm}

El índice h agregado no equivale a la suma ni al promedio de los índices
individuales: indica cuántas publicaciones \(h\) del total analizado
cuentan con \(h\) o más citas.

\end{minipage}%
\end{tcolorbox}

\subsection{Aceso abierto e idiomas de
publicación}\label{aceso-abierto-e-idiomas-de-publicaciuxf3n}

El \textbf{49\% de los artículos analizados} se publicó en revistas de
acceso abierto (Figura~\ref{fig-oa}). Con todo, es posible que esta
cifra sea mayor si se agregan el análisis las publicaciones Scielo, o de
otros repositorios abiertos, que no están registrados en la fuente de
datos.

Respecto al idioma de publicación, predomina el inglés con un 45\%,
seguido del español con un 23\%. La proporción de publicaciones en
inglés es sustancialmente más alta en indexaciones WoS (68\%) que en
Scielo y en Scopus (Figura~\ref{fig-idioma})

\section{Síntesis de indicadores}\label{suxedntesis-de-indicadores}

\begin{longtable}[]{@{}lc@{}}
\caption{Indicadores principales de la producción académica FACSO
(2020-2025)}\label{tbl-sintesis}\tabularnewline
\toprule\noalign{}
Indicador & Valor \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Indicador & Valor \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Publicaciones únicas (2020-2025) & 1.162 \\
Pares publicación-autor & 1.328 \\
Artículos / capítulos / libros & 946 / 171 / 45 \\
Proporción de artículos & 81\% \\
Publicaciones por JCE & 7,8 \\
Artículos en revistas WoS o Scopus & 78\% \\
Publicaciones en revistas Q1 o Q2 (SJR) & 67\% \\
Total de citas / promedio por artículo & 4.854 / 6,7 \\
Índice h institucional & 30 \\
Publicaciones en acceso abierto (no incluye Scielo) & 49\% \\
Idioma predominante (inglés) & 45\% \\
\end{longtable}

\section{Conclusiones}\label{conclusiones}

\subsection{Fortalezas}\label{fortalezas}

Se destaca un volumen alto de productividad académica, que ha
permanecido estable en los últimos años. Asimismo, la producción
académica de FACSO destaca por su nivel de impacto y calidad, con una
proporción importante de la investigación de la Facultad siendo
publicadas en revistas destacadas, que se ubican en los primeros
cuartiles de sus áreas de conocimiento y con alcance internacional.

De tal forma, que la Facultad aloja a un núcleo de investigadores
altamente productivos, con un alto volúmen de publicación que además se
refleja en niveles de impacto sólidos, como se ve reflejados en los
indicadores de citas e índice h.

En la misma línea, se debe relevar la destacada productividad de las
académicas de la Facultad, apareciendo sobre sus pares masculinos en
todos los índicadores observados.

\subsection{Desafíos}\label{desafuxedos}

Se observa una alta concentración en la producción y el impacto
(entendido como cantidad de citas) en una minoría del cuerpo académico.
Esta dispersión se puede observar en brechas existentes entre distintos
grupos. Particularmente, los profesores asistentes y los académicos
mayores de 60 años muestran cifras significativamente más bajas en la
mayoría de los indicadores. Asimismo, se observa una amplia
heterogeneidad en el volumen e impacto de cada departamento de la
Facultad.

\subsection{Oportunidades a futuro}\label{oportunidades-a-futuro}

En términos de políticas de investigación y publicación, los resultados
de este estudio apuntan a la existencia de un fuerte núcleo altamente
productivo que convive con una fuerte concentración y dispersión en
cantidad e impacto de publicaciones. En ese sentido, se abre la
necesidad de pensar políticas focalizadas en determinados grupos de
académicos con el ojetivo de aumentar su productividad y disminuir la
alta dispersión observada.

En tanto, en términos de políticas de gestión de información, la
consolidación de datos de publicaciones aquí realizada abre las puertas
para reportes periódicos que sigan la evolución de estos indicadores.
Asimismo, permite pensar en aplicación de modelos más complejos que
expliquen las diferencias en productividad o analicen mediante
procesamiento de lenguaje natural los temas recurrentes en publicaciones
de la Facultad.

\bookmarksetup{startatroot}

\chapter{Introducción}\label{sec-introduction}

El presente informe expone los resultados del estudio sobre las
publicaciones de académicas y académicos de la Facultad de Ciencias
Sociales (FACSO) de la Universidad de Chile aparecidas entre los años
2020 y 2025. Este estudio se enmarca en el interés de la Facultad por
contar con una caracterización sistemática y actualizada de la
producción académica de sus miembros en un contexto de cierre y balance
de la Decanatura 2022-2026.

Este trabajo continúa y actualiza un primer esfuerzo realizado en 2022,
que caracterizó las publicaciones de la Facultad durante el quinquenio
2015-2019 (\citeproc{ref-moya_publicaciones_}{Moya, 2022}). Aquel
estudio precursor sentó las bases metodológicas y conceptuales para el
diagnóstico de las prácticas de publicación en FACSO, y una de sus
principales recomendaciones fue, precisamente, extender la mirada en el
tiempo mediante un monitoreo periódico que permitiera observar la
evolución de estos indicadores. El presente informe recoge esa
recomendación: retoma el propósito de aquel primer diagnóstico y lo
proyecta sobre un nuevo período, dando continuidad a la línea de trabajo
entonces iniciada.

Con este objetivo se ha recolectado y producido información acerca de
las publicaciones y sus autores. Las publicaciones consideradas en este
estudio comprenden artículos de investigación, capítulos de libros y
libros. Estas formas de publicación reflejan la diversidad de la
productividad académica de las ciencias sociales, así como incluyen
aquellas omúnmente consideradas en la evaluación de la productividad por
parte de las instituciones que financian investigación a nivel nacional
e internacional.

Respecto de su antecesor, este estudio incorporar innovaciones en su
enfoque metodológico. Mientras que el informe de 2022 se apoyó
principalmente en Google Scholar, la presente edición consolida su base
a partir del mantenedor institucional de publicaciones (SEPA-VID),
complementado con la API de ORCID y enriquecido con las principales
fuentes de indexación e impacto ---Web of Science, Scopus, Scielo y
SCImago Journal Rank---. Ello permite caracterizar con mayor precisión
aspectos como la indexación de las revistas, el cuartil en que se
posicionan, el acceso abierto y el número de citas de cada publicación.
Asimismo, el código de análisis utilizado quedará albergado en un
\href{https://github.com/facso-investigacion/publicaciones-facso}{repositorio
en Github de la Dirección de Investigación}, y podrá ser integrado al
sistema de gestión de información científica desarrollado por la misma
Dirección,
\href{https://facso-investigacion.github.io/documentacion-cindai/}{CINDAI}

En este estudio presentamos resultados sobre el volumen y la composición
de la producción académica, su concentración y evolución en el tiempo,
así como características de las publicaciones tales como su nivel de
impacto ---medido a través de las citas y del índice h---, la calidad e
indexación de las revistas, el acceso abierto y el idioma de
publicación. Estos resultados se examinan tanto a nivel agregado de la
Facultad como de forma desagregada según el departamento, el género, la
edad y la jerarquía de los autores, con el fin de identificar perfiles,
fortalezas y brechas al interior de la comunidad académica.

A continuación, se describen la \href{02-metodologia.qmd}{metodología}
empleada en la construcción y el análisis de la base de datos. Luego se
presentan los \href{03-resultados.qmd}{resultados}, organizados en torno
a la caracterización general de la producción y al análisis específico
de los artículos y las revistas en que se publican. Finalmente, se un
conjunto de \href{04-conclusiones.qmd}{conclusiones} orientadas a
relevar fortalezas, desafíos y oportunidades para la Facultad, así como
a nutrir el debate en torno a las políticas de investigación y
publicación en el cierre de este período y de cara a los desafíos
futuros.

\bookmarksetup{startatroot}

\chapter{Metodología}\label{sec-methods}

\section{Datos}\label{datos}

\subsection{Publicaciones}\label{publicaciones}

La principal fuente de datos para publicaciones fue el mantenedor de
publicaciones de SEPA-VID gestionado por la Unidad de Datos e
Indicadores de la VID. Se filtraron las publicaciones adscritas a la
Facultad de Ciencias Sociales para el período comprendido entre 2020 y
2025. Cabe destacar que SEPA-VID contiene únicamente las publicaciones
de un académicos durante la vigencia de su nombramiento en la
Universidad, por lo que publicaciones previas al ingreso de un académico
no se consideran en el análisis. Además, SEPA-VID contiene
mayoritaríamente artículos indexados en las bases de datos de WoS,
Scopus y Scielo.

Esta base fue complementada a través de la API de ORCID para los 72
investigadores incluídos en el
\href{https://colaboratoriocienciassociales.uchile.cl/}{Colaboratorio de
Investigación en Ciencias Sociales} de la Facultad. Este procedimiento
resultó particularmente útil para recoger información de libros,
capítulos de libros y artículos indexados en bases de datos distintas a
las mencionadas.

Además, la base fue enriquecida a través de la
\href{https://www.webofscience.com/wos/mjl/collection-list-downloads}{Web
of Science Master List}, la
\href{https://www.elsevier.com/products/scopus/content\#4-titles-on-scopus}{Scopus
Source title list} y la API de Scielo con el fin de identificar la
indexación de revistas sin ese registro. Además, se extrajo de estas
listas información sobre el idioma de la revista o si la publicación
tiene acceso abierto. Se utilizó la API de Scopus para recoger la
cantidad de citas para cada publicación identificada. Por último, se
utilizó el \href{https://www.scimagojr.com/journalrank.php}{SCImago
Journal Rank} para obtener información sobre impacto y el cuartil en que
se posicionan las revistas registradas.

\subsection{Académicos}\label{acaduxe9micos}

Se utilizó la base de personal académico de la Facultad de Ciencias
Sociales para extraer información sobre características del cuerpo
académico de la Facultad. Se incluyeron en este estudio todos los
nombramientos vigentes al 31 de diciembre del 2025, excluyendo a los
investigadores postdoctorales.

\section{Variables}\label{variables}

La variable principal del estudio son las publicaciones producidas por
académicos y académicas de la Facultad de Ciencias Sociales entre 2020 y
2025. Se incluyeron en el estudio tres tipos de publicaciones: artículos
de revistas, capítulos de libros y libros. Con la información
disponible, no fue posible distinguir entre libros monográficos y libros
editados, por lo que la etiqueta ``libros'' aplica a ambos tipos de
publicaciones. Se exluyeron del análisis material editorial,
corecciones, cartas, revisiones de libros y otros tipos de publicaciones
menores. De tal modo, se incluyeron en el análisis un total 1162
publicaciones diferentes, de las cuales la mayoría corresponden a
artículos (946), seguido de 171 capítulos de libros y 45 libros. Dado
que una publicación puede tener más de un autor perteneciente a la
Facultad, se encontaron un total de 1328 publicaciones-autor.

Se consideraron, adeás, variables de caracterización de los académicos
de la Facultad tales como departamento, género, edad y jerarquía. Para
posibilitar la comparación entre estas variables, la mayoría de los
análisis se ponderaron por Jornadas Completas Equivalentes (JCE),
calculadas como:

\[JCE = \frac{\sum_{i=1}^{n} h_i}{44}\]

Donde:

\begin{itemize}
\item
  \(h_i\) = horas reales de dedicación académica de la persona \(i\)
\item
  \(n\)= número total de personas consideradas en el cálculo
\item
  \(44\)= número de horas semanales definidas como una jornada completa
\end{itemize}

Se tomó como referencia los académicos con nombramiento vigente al 31 de
diciembre de 2025. En total, se encontraron 148.91 JCE. En la
Tabla~\ref{tbl-acad}, se presenta un resumen desagregado de Jornada
Completas Equivalente por departamento, género, edad y jerarquía.

\begin{table}

\caption{\label{tbl-acad}Jornadas Completas Equivalente Facultad de
Ciencias Sociales}

\centering{

\centering
\begin{tabular}[t]{l|c}
\hline
Grupo & JCE\\
\hline
\multicolumn{2}{l}{\textbf{Total}}\\
\hline
\hspace{1em}Total & 148.91\\
\hline
\multicolumn{2}{l}{\textbf{Departamento}}\\
\hline
\hspace{1em}Antropología & 32.84\\
\hline
\hspace{1em}Educación & 19.09\\
\hline
\hspace{1em}Postgrado & 0.61\\
\hline
\hspace{1em}Psicología & 45.09\\
\hline
\hspace{1em}Sociología & 28.77\\
\hline
\hspace{1em}Trabajo social & 22.50\\
\hline
\multicolumn{2}{l}{\textbf{Sexo}}\\
\hline
\hspace{1em}Femenino & 72.50\\
\hline
\hspace{1em}Masculino & 76.41\\
\hline
\multicolumn{2}{l}{\textbf{Tramo de edad}}\\
\hline
\hspace{1em}Menos de 50 años & 48.95\\
\hline
\hspace{1em}50 a 59 años & 61.84\\
\hline
\hspace{1em}60 años o más & 38.11\\
\hline
\multicolumn{2}{l}{\textbf{Jerarquía}}\\
\hline
\hspace{1em}Adjunto & 4.11\\
\hline
\hspace{1em}Asistente & 55.27\\
\hline
\hspace{1em}Asociado & 64.61\\
\hline
\hspace{1em}Titular & 24.91\\
\hline
\end{tabular}

}

\end{table}%

En el caso de los artículos, se utilizaron variables de caracterización
tales como:

\begin{itemize}
\item
  Indexación (WoS, Scopus, Scielo, Otras). En caso de las revists
  multindexadas, se estableció una jerarquía basada en el prestigio,
  exigencia y ponderación otorgada en los grupos de evaluación Fondecyt:
  WoS \textgreater{} Scopus \textgreater{} Scielo \textgreater{} Otras.
  Es decir, si una revista se encuentra indexada tanto en WoS como en
  Scopus, se consideró exclusivamente como WoS; Si se encuentra en
  Scopus y en Scielo, pero no en WoS, se contabilizó como Scopus. Lo
  mismo con Scielo respecto a la categoría ``Otra''. Esta última
  categoría incluye publicaciones el \emph{Emerging Sources Citacion
  Index} (ESCI), la \emph{European Reference Index for the Humanities
  and Social Sciences} (ERIH Plus), \emph{Latindex}, el \emph{Directory
  of Open Access Journals} (DOAJ), entre otras.
\item
  Número de Citas (Scopus)
\item
  Cuartil de Revistas (SJR)
\item
  Acceso abierto
\item
  Idioma
\end{itemize}

Dado que la base final se construyó desde diversas fuentes, el tamaño
real de los datos analizados puede cambiar para cada variable. En
Tabla~\ref{tbl-datos} se resume la cantidad de artículos que cuentan con
datos válidos para cada variable antes mencionada.

\begin{table}

\caption{\label{tbl-datos}N analítico por variable de análisis}

\centering{

\centering
\begin{tabular}[t]{l|c}
\hline
Variable & N\\
\hline
Indexación & 937\\
\hline
Cuartil & 736\\
\hline
N° de citas & 703\\
\hline
Acceso abierto (OA) & 737\\
\hline
Idioma & 829\\
\hline
\end{tabular}

}

\end{table}%

Por útlimo, como medida complementaria para medir el impacto académico
de las publicaciones analizadas, se calculoó un índice h agregado a
nivel de Facultad y departamento, así como por género, edad y jerarquía.
Este índice no debe entenderse como la suma o el promedio de los índice
h individuales de los académicos de la Facultad. Más bien, indica
cuántas publicaciones \(h\), del total analizado, cuentan con \(h\) o
más citas.

\section{Métodos}\label{muxe9todos}

Se realizó un análisis cuantitativo descriptivo a partir de las
variables antes introducidas. Para análisis agregados a nivel de la
Facultad se tomaron como referencias las publicaciones únicas
identificadas (n= 1162). En cambio, para la caracterización a partir del
género, edad y jerarquía de los autores, se utilizaron como unidad de
análisis cada par de publicación-autor.

Las bases de datos fueron recolectadas, procesadas y analizadas mediante
el lenguaje de programación R. Los datos y el código de análisis,
incluyendo el que produce este documento, se encuentran alojadas en un
\href{https://github.com/facso-investigacion/publicaciones-facso}{repositorio
de la Dirección de Investigación en Github}.

En el caso de los artículos, se analizó tanto volúmen como cantidad de
citas, impacto, indexación, acceso abierto e idioma. En cambio, dada la
baja calidad de la información relativa a libros y capítulos de libros,
se optó por limitar su análisis al volúmen de producción y sus cruces
con características de los autores.

\bookmarksetup{startatroot}

\chapter{Resultados}\label{sec-results}

\section{Caractertización de las publicaciones de académicos
FACSO}\label{caractertizaciuxf3n-de-las-publicaciones-de-acaduxe9micos-facso}

\subsection{Volúmen total de Publicaciones
(2020-2025)}\label{voluxfamen-total-de-publicaciones-2020-2025}

\begin{figure}

\caption{\label{fig-tipo-publicaciones}Cantidad de publicaciones por
tipo de publicación}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{03-resultados_files/figure-pdf/fig-tipo-publicaciones-1.pdf}}

}

\end{figure}%

En el período de referencia (2020-2025), se encontraron un total de 1162
publicaciones diferentes. Entre estas, como se expone en la
Figura~\ref{fig-tipo-publicaciones}, se observa un claro dominio de la
publicación de artículos en revistas académicas (n=946), representando
un 81\% del total de publicaciones identificadas. Los capítulos de
libros en libros editados, en tanto, representan un 15\% del total,
mientras que los libros monográficos o editados son solo el 4\% del
volumen total de publicaciones. Considerando que al 31 de diciembre de
2025 la Facultad contaba con 155 Jornadas Completas Equivalente (JCE),
esto significa que el período estudiado se registraron 7.8 publicaciones
por JCE: 6.35 artículos, 1.15 capítulos de libros y 0.3 libros.

\begin{figure}

\caption{\label{fig-publicacion-anio}Publicaciones por año}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{03-resultados_files/figure-pdf/fig-publicacion-anio-1.pdf}}

}

\end{figure}%

Observando la evolución por año en el período de referencia se aprecia
que entre 2020 y 2021 aumentaron la cantidad de publicaciones de manera
sustancial para los tres tipos de publicaciones analizadas, posiblemente
por un efecto de rebote tras el inicio de la Pandemia por COVID19 en
2020. Desde ahí, se observan fluctuaciones con relativa estabilidad.
Así, los artículos se mantienen entre 148 y 185, los capítulos de libro
entre 22 y 39, y entre 3 y 11 libros monográficos o editados.

La mediana de publicaciones por académico es de 3, con el 50\% de la
Facultad produciendo entre 1 y 9 publicaciones en el período mencionado,
con máximos que llegan hasta las 45 publicaciones. Esto indica una alta
dispersión y una concentración de publicaciones entre los académicos más
productivos, como se observan en la Figura~\ref{fig-publicacion-lorenz}.
Así, el 20\% de los académicos más productivos concentra dos tercios de
las publicaciones; el 50\% del total de las publicaciones de la Facultad
corresponden al 13\% de los académicos con mayor productividad.

\begin{figure}

\caption{\label{fig-publicacion-lorenz}Concentración de publicaciones
por porcentaje de académicos acumulado (2020-2025)}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{03-resultados_files/figure-pdf/fig-publicacion-lorenz-1.pdf}}

}

\end{figure}%

\subsection{Caracterización de los
autores}\label{caracterizaciuxf3n-de-los-autores}

Según se observa en el Figura~\ref{fig-publicacion-depto}, el predominio
de los artículos sobre otras formas de publicaciones es apreciable en
todos los departamentos, aunque la publicación de capítulos de libros es
superior en Trabajo Social, Sociología y Psicología. Se destaca que el
departamento de Trabajo Social es el que más publicaciones por Jornada
Completa Equivalente (2025) produce, con 13.9 publicaciones por JCE. Le
sigue el Departamento de Sociología con 9.4 publicaciones por JCE,
Psicología con 8.5, Antropología con 8.2 y Educación con 4.7.

\begin{figure}

\begin{minipage}{\linewidth}

\begin{figure}[H]

\caption{\label{fig-publicacion-depto}Publicaciones por Departamento por
JCE (2020-2025)}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{03-resultados_files/figure-pdf/fig-publicacion-depto-1.pdf}}

}

\end{figure}%

\end{minipage}%

\end{figure}%

En la Figura~\ref{fig-publicacion-genero} se observa que las académicas
de la Facultad son más productivas que los académicos, completando 10.73
publicaciones por JCE en le período analizado, contra 7.19 publicaciones
por JCE entre los hombres. Aunque esta diferencia se repite en todos los
tipos de publicaciones, es más acentuada en los artículos, con una
diferencia 2.71 publicaciones por jornada completa.

\begin{figure}

\caption{\label{fig-publicacion-genero}Publicaciones por Género
(2020-2025)}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{03-resultados_files/figure-pdf/fig-publicacion-genero-1.pdf}}

}

\end{figure}%

El Figura~\ref{fig-publicacion-edad} muestra que el tramo etario con
mayor productividad en el período analizado se encuentra entre los 50 y
59 años, con 10.58 publicaciones por JCE, y fuerte concentración en los
artículos. Le sigue el grupo menor de 50 años, con 10.03 publicaciones
por JCE, aunque con un menor peso relativo de los artículos en
comparación a los capítulos de libro. Mientras tanto, la productividad
de los académicos mayores de de 60 años es de 4.79 publicaciones por
JCE.

\begin{figure}

\caption{\label{fig-publicacion-edad}Publicaciones por Edad y
Departamento (2020-2025)}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{03-resultados_files/figure-pdf/fig-publicacion-edad-1.pdf}}

}

\end{figure}%

LA Figura~\ref{fig-publicacion-jerarquia} muestra las diferencias por
jerarquía. Se observa que hay un salto importante entre la jerarquía de
asistente y de asociado, pasando de 4.49 publicaciones por JCE a 12.19.
La diferencia entre profesores asociados y titulares es menor, con los
segundos registrando 11.49 publicaciones por JCE.

\begin{figure}

\caption{\label{fig-publicacion-jerarquia}Publicaciones por Jerarquía y
Departamento (2020-2025)}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{03-resultados_files/figure-pdf/fig-publicacion-jerarquia-1.pdf}}

}

\end{figure}%

\section{Artículos y Revistas}\label{artuxedculos-y-revistas}

\subsection{Indexaciones}\label{indexaciones}

Los artículos de investigación representan con diferencia la mayor parte
de la producción académica de la Facultad, con 946 registros diferentes,
o un 77\% del total de las publicaciones identificadas. La
Figura~\ref{fig-index} muestra la distribución de las indexaciones de
las revistas en que publican los académicos de FACSO. De tal modo, se
observa que el 78\% de las publicaciones se encuentran en revistas
indexadas en WoS (42\%) o Scopus (36\%), posiblemente en consonancia con
los modelos de evaluación de ANID en sus fondos concursables. Más abajo
se encuentran las revistas indexadas en Scielo, con un 11\% de las
publicaciones en el período analizada. La categoría ``Otra'' agrega
revistas en indexadas en el \emph{Emerging Sources Citacion Index}
(ESCI), la \emph{European Reference Index for the Humanities and Social
Sciences} (ERIH Plus), \emph{Latindex}, el \emph{Directory of Open
Access Journals} (DOAJ), entre otras.

\begin{figure}

\caption{\label{fig-index}Publicaciones por Indexación de la Revista
(2020-2025)}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{03-resultados_files/figure-pdf/fig-index-1.pdf}}

}

\end{figure}%

\begin{figure}

\caption{\label{fig-index-evolucion}Evolución de Publicaciones por
Indexación de la Revista (2020-2025)}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{03-resultados_files/figure-pdf/fig-index-evolucion-1.pdf}}

}

\end{figure}%

La Figura~\ref{fig-index-evolucion} muestra la evolución de la cantidad
de publicaciones en cada indexación durante el período analizado. La
predominancia de WoS y Scopus se mantiene en todo los años,
particularmente tras la recuperación post-pandemia en 2021. Durante 2021
y 2022, prácticamente no hay diferencias entre ambas bases de datos. Sin
embargo, desde 2023 se abre una brecha en favor a Web of Science que ha
fluctuado entre 7 y 12 publicaciones por año. También es interesante que
las publicaciones indexadas en Scielo se habían mantenido entrw 14 y 22,
incluso en 2020 durante la pandemia, para caer bruscamente en 2025. Por
supuesto, no es posible establecer aún las causas o si esto es una
tendencia que se mantendrá en el tiempo.

\begin{figure}

\caption{\label{fig-index-depto}Publicaciones por Indexación de la
Revista por Departamento (2020-2025)}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{03-resultados_files/figure-pdf/fig-index-depto-1.pdf}}

}

\end{figure}%

La Figura~\ref{fig-index-depto} muestra que hay diferencias importantes
entre los departamentos. Por un lado, en Antropología predominan las
publicaciones en WoS, principalmente en revistas relaciondas a la
arqueología y la antropología física. Mientras tanto, el Departamento de
Trabajo Social muestra una mayor cantidad de publicaciones en Scopus por
JCE, al igual que el Departamento de Educación. El Departamento de
Psicología y el Departamento de Sociología, por su lado, muestran un
mayor nivel de paridad entre entre ambas bases de datos, con un leve
predominio de WoS. La Tabla~\ref{tbl-index-depto} muestra las revistas
con mayor frecuencia por departamento, reflejando las tendencias antes
mencionadas. Asimismo, se observa una fuerte presencia de la revistas de
la Facultad, tales como Enfoques Educaciones (Departamento de
Educación), Revista de Psicología (Departamento de Psicología), Última
Década y Revista de Sociología (Departamento de Sociología), y
Propuestas Críticas en Trabajo Social y Revista MAD (Departamento de
Trabajo Social).

\begin{table}

\caption{\label{tbl-index-depto}Revistas con mayor cantidad de
publicaciones por Departamento (2020-2025)}

\centering{

\centering
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{11cm}lr}
\toprule
Publicación & Indexación & Frecuencia\\
\midrule
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Antropología}}\\
\hspace{1em}CHUNGARA-REVISTA DE ANTROPOLOGIA CHILENA & WoS & 11\\
\hspace{1em}JOURNAL OF ARCHAEOLOGICAL SCIENCE-REPORTS & WoS & 8\\
\hspace{1em}ESTUDIOS ATACAMENOS & WoS & 6\\
\hspace{1em}MAGALLANIA & WoS & 6\\
\hspace{1em}QUATERNARY INTERNATIONAL & WoS & 5\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Educación}}\\
\hspace{1em}ESTUDIOS PEDAGOGICOS (VALDIVIA) & Scopus & 6\\
\hspace{1em}Revista enfoques educacionales & Scielo & 5\\
\hspace{1em}Revista de estudios y experiencias en educación & Scielo & 4\\
\hspace{1em}Dialogo andino & Scopus & 2\\
\hspace{1em}REVISTA COMPLUTENSE DE EDUCACION & Scopus & 2\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Psicología}}\\
\hspace{1em}Revista de psicología & Scielo & 10\\
\hspace{1em}Psykhe & Scopus & 8\\
\hspace{1em}PSICOPERSPECTIVAS & Scopus & 6\\
\hspace{1em}TERAPIA PSICOLOGICA & WoS & 5\\
\hspace{1em}SUSTAINABILITY & WoS & 4\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Sociología}}\\
\hspace{1em}ULTIMA DECADA & Scielo & 7\\
\hspace{1em}Revista de Sociología & Otra & 7\\
\hspace{1em}Estudios Sociologicos & Scopus & 5\\
\hspace{1em}FRONTIERS IN SOCIOLOGY & Scopus & 4\\
\hspace{1em}Revista Chilena de Derecho y Ciencia Política & Scopus & 4\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Trabajo social}}\\
\hspace{1em}Propuestas Críticas en Trabajo Social-Critical Proposals in Social Work & Otra & 24\\
\hspace{1em}REVISTA MAD-REVISTA DEL MAGISTER EN ANALISIS SISTEMICO APLICADO A LA SOCIEDAD & Scopus & 10\\
\hspace{1em}RUMBOS TS Un Espacio Crítico para la Reflexión en Ciencias Sociales & Scielo & 6\\
\hspace{1em}FRONTIERS IN PSYCHOLOGY & WoS & 4\\
\hspace{1em}SOCIAL WORK EDUCATION & Scopus & 4\\
\bottomrule
\end{tabular}

}

\end{table}%

Figura~\ref{fig-index-carac} muestra la cantidad de publicaciones por
JCE según género, edad y jerarquía de los autores. En general, se
aprecia que las tendencias observadas son las mismas, con WoS y Scopus
acaparando la mayor parte de la productividad, y la primera estando
sobre la segunda en la mayoría de los grupos analizados. También se
mantienen tendencias tales como que las mujeres
(Figura~\ref{fig-index-carac-1}) y los académicos de entre 50 y 59 años
(Figura~\ref{fig-index-carac-2}) publican más en todas las indexaciones.
Respecto a la jerarquía, como se observa en
Figura~\ref{fig-index-carac-3}, mientras los profesores titulares son
quienes más publican en WoS por JCE, los profesores asociados los
superan en Scopus y Scielo.

\begin{figure}[H]

\caption{\label{fig-index-carac}Publicaciones por Indexación y
características de los autores}

\centering{

\subcaption{\label{fig-index-carac-1}Publicaciones por Indexación de la
Revista por Género del autor(2020-2025)}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{03-resultados_files/figure-pdf/fig-index-carac-1.pdf}}

}

\subcaption{\label{fig-index-carac-2}Publicaciones por Indexación de la
Revista por Edad del autor(2020-2025)}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{03-resultados_files/figure-pdf/fig-index-carac-2.pdf}}

}

\subcaption{\label{fig-index-carac-3}Publicaciones por Indexación de la
Revista por Jerarquia del autor(2020-2025)}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{03-resultados_files/figure-pdf/fig-index-carac-3.pdf}}

}

}

\end{figure}%

\subsection{Número de Citas}\label{nuxfamero-de-citas}

A través de la API de Scopus, se encontraron registro de las citas de
674 artículos durante el período estudiado. La suma de citas entre 2020
y 2025 asciende a un total de 4854, lo que equivale a un promedio de 6.7
citas por artículos. Si se ordenan las citas de mayor a menor, es
posible observar que el índice h agregado de la institución es igual a
30. En otras palabras, entre 2020 y 2025 los académicos de la Facultad
publicaron un total de 30 artículos que registran 30 citas o más.

Ahora bien, se observa una gran dispersión en la cantidad de citas por
artículo. El rango de citas va de 0 a un máximo de 307. El artículo
mediano cuenta con 3 citaciones, con el 50\% de las publicaciones
registrando entre 1 y 7 citas. Esta amplia dispersión se observa
claramente en Figura~\ref{fig-citas-densidad}, donde se observa una
mayor proporción de artículos con 0 a 2 citas, con una cola larga hacia
la derecha que se extiende más allá de las 300 citas.

\begin{figure}

\caption{\label{fig-citas-densidad}Distribución de citas por artículos
(2020-2025)}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{03-resultados_files/figure-pdf/fig-citas-densidad-1.pdf}}

}

\end{figure}%

La Tabla~\ref{tbl-citas-depto} muestra la cantidad de artículo, el total
de citas y el índice h para cada Departamento de la Facultad. El
departamento de Psicología tiene la mayor cantidad de citas en el
período analizado, con 2148 citas y un índice h de 22. Le siguen el
departamento de Antropología con 1169 citas y un índice h de 16; el
departamento de Sociología con 951 citas y un índice h de 15; el
departamento de Trabajo Social y el departamento de Educación con 90
citas y un índice h de 5.

\begin{longtable}[t]{lccc}

\caption{\label{tbl-citas-depto}Citas e Indíce h por Departamento
(2020-2025)}

\tabularnewline

\toprule
Departamento & Artículos & Total de citas & Índice h\\
\midrule
Antropología & 178 & 1169 & 16\\
Educación & 36 & 90 & 5\\
Psicología & 217 & 2148 & 22\\
Sociología & 134 & 951 & 15\\
Trabajo social & 139 & 774 & 12\\
\bottomrule

\end{longtable}

La Tabla~\ref{tbl-citas} permite aprecias las diferencias en la cantidad
de citas e índice h según género, edad y jerarquía académica. Se
observan tendencias similares a las que expusieron respecto al volúmen
de publicación. Las mujeres exhiben una mayor cantidad de citas y un
mayor índice h que los hombres, pese a representar una cantidad menor de
JCE en la Facultad. Los académicos entre 50 y 59 años, y auquellos con
jerarquía académica de Asociado, presentan la mayor cantidad de citas e
índice h. Cabe destacar, con todo, que la diferencia en la cantidad de
citas entre profesores asociados y titulares se explica mayormente por
la menor cantidad de académicos en la jerarquía titular.

\begin{longtable}[t]{lccc}

\caption{\label{tbl-citas}Citas e Indíce h por características de los
autores (2020-2025)}

\tabularnewline

\toprule
Categoría & Artículos & Total de citas & Índice h\\
\midrule
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Género}}\\
\hspace{1em}Femenino & 464 & 3566 & 26\\
\hspace{1em}Masculino & 342 & 2121 & 22\\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Tramo de edad}}\\
\hspace{1em}Menos de 50 años & 271 & 1361 & 16\\
\hspace{1em}50 a 59 años & 426 & 3449 & 25\\
\hspace{1em}60 años o más & 109 & 877 & 15\\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Jerarquía académica}}\\
\hspace{1em}Asistente & 153 & 792 & 12\\
\hspace{1em}Asociado & 473 & 3553 & 27\\
\hspace{1em}Titular & 178 & 1341 & 17\\
\bottomrule

\end{longtable}

\subsection{Cuartil de las revistas}\label{cuartil-de-las-revistas}

Se registraron un total de 741 publicaciones en revistas con un SJR
(\emph{SCImago Journal Rank}) registrado. La Tabla~\ref{tbl-sjr} muestra
la distribución por Cuartil de SJR de las publicaciones analizadas. Se
destaca que la mayoría de las publicación se encuentran en el rango de
Q1, con un 42\%. En conjunto, el 67\% de las publicaciones en revistas
con factor de impacto en SCImago durante el período de referencia
corresponden a revitas Q1 o Q2.

\begin{table}

\caption{\label{tbl-sjr}Cuartil en SJR publicaciones FACSO (2020-2025)}

\centering{

\centering
\begin{tabular}[t]{lrr}
\toprule
\cellcolor[HTML]{f2f2f2}{\textbf{Cuartil}} & \cellcolor[HTML]{f2f2f2}{\textbf{N}} & \cellcolor[HTML]{f2f2f2}{\textbf{Porcentaje}}\\
\midrule
Q1 & 310 & 42,2\%\\
Q2 & 187 & 25,4\%\\
Q3 & 181 & 24,6\%\\
Q4 & 57 & 7,8\%\\
\bottomrule
\end{tabular}

}

\end{table}%

La Figura~\ref{fig-sjr} muestra la evolución de la cantidad y proporción
de de publicacione de académicos FACSO en revistas Q1 y Q2 durante el
período de referencia. Como era de esperar, se repite el patrón de
recuperación tras el 2020, alcanzando un peak en de 103 publicaciones Q1
o Q2 que representan un 73\% del total de artículos con SJR. Desde ahí,
se produce una tendencia a la baja hasta 2023, revirtiendose para 2024.
En 2025, se vuelve a niveles similares a 2021 on 102 publicaciones Q1 o
Q2, lo que representa un 70\% de los artículos analizados.

\begin{figure}

\caption{\label{fig-sjr}Evolución Cantidad y Proporción de Publicación
FACSO en revistas Q1 y Q2 (2020-2025)}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{03-resultados_files/figure-pdf/fig-sjr-1.pdf}}

}

\end{figure}%

La Figura~\ref{fig-sjr-depto} permite describir el volúmen y la
proporción de publicaciones en revistas Q1y Q2 por departamento,
ajustadas por JCE. Antropología destaca por tener la mayor cantidad de
publicaciones Q1 y Q2 durante el período analizado, con 4.4 artículos
por JCE. Asimismo, es el departamento que tiene una mayor proporción de
artículos en estas categorías. Por su lado, el Departamento de Trabajo
Social registra la mayor cantidad de publicaciones en revistas Q1, con
2.8 artículos por JCE.

\begin{figure}

\caption{\label{fig-sjr-depto}Cantidad y proporción de publicaciones en
revistas Q1 y Q2 por JCE por Departamento (2020-2025)}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{03-resultados_files/figure-pdf/fig-sjr-depto-1.pdf}}

}

\end{figure}%

La Tabla~\ref{tbl-sjr-depto} expone las principales revistas Q1 o Q2 en
que han publicado los académicos de la Facultad durante el período
analizado. Los resultados son similares a los observados en
Tabla~\ref{tbl-index-depto}, especialmente en Antropología y Trabajo
Social. Destacan publicaciones en revistas tales como \emph{Earth
Future} (Q1 en Ciencias del Medioambiente), \emph{Journal of
Archaeological Science} (Q1 en Arqueología), \emph{BMC Psychiatry} (Q1
en Psiquiatría y Salud Mental), \emph{Frontiers in Sociology} (Q1 en
Ciencias Sociales) y \emph{Frontiers in Psychology} (Q1 en Psicología).
Por otro lado, vuelve a aparecen una revista de la Facultad:
\emph{Cintia de Moebio}, que se encuentra calificada como Q2 en el área
de Filosofía.

\begin{table}

\caption{\label{tbl-sjr-depto}Revistas con mayor cantidad de
publicaciones por Departamento (2020-2025)}

\centering{

\centering
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{11cm}lr}
\toprule
Publicación & Cuartil & Frecuencia\\
\midrule
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Antropología}}\\
\hspace{1em}CHUNGARA-REVISTA DE ANTROPOLOGIA CHILENA & Q2 & 11\\
\hspace{1em}JOURNAL OF ARCHAEOLOGICAL SCIENCE-REPORTS & Q1 & 8\\
\hspace{1em}ESTUDIOS ATACAMENOS & Q2 & 6\\
\hspace{1em}MAGALLANIA & Q2 & 6\\
\hspace{1em}QUATERNARY INTERNATIONAL & Q2 & 5\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Educación}}\\
\hspace{1em}Dialogo andino & Q1 & 2\\
\hspace{1em}EARLY YEARS & Q2 & 2\\
\hspace{1em}FRONTIERS IN PSYCHOLOGY & Q1 & 1\\
\hspace{1em}EDUCATION POLICY ANALYSIS ARCHIVES & Q2 & 1\\
\hspace{1em}PSICOPERSPECTIVAS & Q2 & 1\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Psicología}}\\
\hspace{1em}PSICOPERSPECTIVAS & Q2 & 6\\
\hspace{1em}SUSTAINABILITY & Q1 & 4\\
\hspace{1em}BMC PSYCHIATRY & Q1 & 4\\
\hspace{1em}INTERNATIONAL JOURNAL OF ENVIRONMENTAL RESEARCH AND PUBLIC HEALTH & Q1 & 3\\
\hspace{1em}JOURNAL OF COMMUNITY PSYCHOLOGY & Q1 & 3\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Sociología}}\\
\hspace{1em}FRONTIERS IN SOCIOLOGY & Q1 & 4\\
\hspace{1em}LATIN AMERICAN RESEARCH REVIEW & Q1 & 3\\
\hspace{1em}CINTA DE MOEBIO & Q2 & 3\\
\hspace{1em}CUHSO-CULTURA-HOMBRE-SOCIEDAD & Q2 & 3\\
\hspace{1em}HISTORIA-SANTIAGO & Q1 & 2\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Trabajo social}}\\
\hspace{1em}FRONTIERS IN PSYCHOLOGY & Q1 & 4\\
\hspace{1em}SOCIAL WORK EDUCATION & Q1 & 4\\
\hspace{1em}BRITISH JOURNAL OF SOCIAL WORK & Q1 & 4\\
\hspace{1em}AFFILIA-FEMINIST INQUIRY IN SOCIAL WORK & Q1 & 4\\
\hspace{1em}EARTHS FUTURE & Q1 & 3\\
\bottomrule
\end{tabular}

}

\end{table}%

En Tabla~\ref{tbl-sjr-carac} se muestran las diferencias por
características del autor en la cantidad y proporción de publicaciones
en Q1 y Q2. En líneas generales, todos los grupos muestran proporciones
de publicación en estas categorías sobre el 60\%, con porcentajes
especialmente altos entre las mujeres (71\%) y los profesores titulares
(72\%). Nuevamente, las académicas mujeres muestran una mayor
productividad que sus pares masculinos, publicando 1.8 artículos más por
JCE. La diferencia entre académicos menores de 50 años y aquellos entre
50 y 59 es menor, pero la cantidad de publicaciones cae bruscamente en
el grupo mayor de 60. Por último, se observa una gran brecha entre los
profesores asistentes y los asociados o titulares, con estos últimos
mostrando una productividad levemente superior (0.5 artículos más por
JCE, en relación a la jerarquía de Asociado).

\begin{table}

\caption{\label{tbl-sjr-carac}Cantidad por JCE y proporción de
publicaciones en revistas Q1 y Q2 por características del autor
(2020-2025)}

\centering{

\centering
\begin{tabular}[t]{ccc}
\toprule
\cellcolor[HTML]{f2f2f2}{\textbf{Categoría}} & \cellcolor[HTML]{f2f2f2}{\textbf{Publicaciones por JCE}} & \cellcolor[HTML]{f2f2f2}{\textbf{\% Q1+Q2}}\\
\midrule
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Género}}\\
\hspace{1em}Femenino & 4.9 & 71\%\\
\hspace{1em}Masculino & 3.1 & 62\%\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Edad}}\\
\hspace{1em}Menos de 50 años & 4.1 & 66\%\\
\hspace{1em}50 a 59 años & 5.0 & 68\%\\
\hspace{1em}60 años o más & 2.1 & 65\%\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Jerarquía}}\\
\hspace{1em}Asistente & 2.1 & 68\%\\
\hspace{1em}Asociado & 5.2 & 65\%\\
\hspace{1em}Titular & 5.7 & 72\%\\
\bottomrule
\end{tabular}

}

\end{table}%

\subsection{Revistas de Acceso
Abierto}\label{revistas-de-acceso-abierto}

A partir de las base de revistas de Scopus, es posible analizar los
artículos de académicos de la Facultad publicadas en revistas de acceso
abierto\footnote{Acceso abierto implica que el usuario puede acceder de
  manera gratuita a los artículos publicados. Con los datos disponibles,
  no es posible distinguir si esto implica o no el pago de un APC por
  parte del autor.}. Se encontró información para 746 artículos. Cabe
destacar, que aunque muchas revistas que están indexadas en Scielo se
encuentran en Scopus, no siempre es el caso. Por ello, dado que Scielo
requiere que las revistas que integran su base de datos sean de acceso
abierto, es muy posible que la cantidad de artículos de libre acceso
publicados en la Facultad sea mayor que la aquí reportada.

Hecha esa consideración metodológica, se observa que 362 publicaciones,
o un 49\% de los artículos analizados, fueron publicados en revistas de
acceso abierto. Entre revistas indexadas en Scopus, esta cifra alcanza
el 70\%; Para Web of Science, en cambio, es del solo el 30\%. En
Figura~\ref{fig-oa}, se grafica la evolución de este indicador en el
período estudiado. Se observa un peak durante la pandemia en 2020, con
un 56\%, para luego bajar y mantenerse estable en los años subsiguiente,
oscilando entre un 44\% y un 50\%.

\begin{figure}

\caption{\label{fig-oa}Porcentaje de publicaciones en revistas de acceso
abierto (2020-2025)}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{03-resultados_files/figure-pdf/fig-oa-1.pdf}}

}

\end{figure}%

Como se puede apreciar en a Tabla~\ref{tbl-oa}, las tendencias se
mantienen bastante constante en distintos grupos. La proporción de
publicaciones en acceso abieto es algo superior en los Departamento de
Sociología (52\%) y Trabajo Social (55\%), académicos de 50 a 59 años
(53\%) y profesores asociados (53\%). En cambio, es algo menor en los
académicos menores de 50 años (42\%) y los profesores con jerarquía
académicas de Asistente (41\%)

\begin{table}

\caption{\label{tbl-oa}Cantidad y porcentaje de publicaciones en acceso
abierto por características del autor (2020-2025)}

\centering{

\centering\begingroup\fontsize{13}{15}\selectfont

\begin{tabular}[t]{lrr}
\toprule
\cellcolor[HTML]{f2f2f2}{\textbf{Categoría}} & \cellcolor[HTML]{f2f2f2}{\textbf{N publicaciones OA}} & \cellcolor[HTML]{f2f2f2}{\textbf{\% en acceso abierto}}\\
\midrule
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Departamento}}\\
\hspace{1em}\cellcolor{gray!10}{Antropología} & \cellcolor{gray!10}{86} & \cellcolor{gray!10}{46\%}\\
\hspace{1em}Educación & 18 & 47\%\\
\hspace{1em}\cellcolor{gray!10}{Psicología} & \cellcolor{gray!10}{109} & \cellcolor{gray!10}{48\%}\\
\hspace{1em}Sociología & 78 & 52\%\\
\hspace{1em}\cellcolor{gray!10}{Trabajo social} & \cellcolor{gray!10}{81} & \cellcolor{gray!10}{56\%}\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Sexo}}\\
\hspace{1em}Femenino & 242 & 48\%\\
\hspace{1em}\cellcolor{gray!10}{Masculino} & \cellcolor{gray!10}{180} & \cellcolor{gray!10}{48\%}\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Edad}}\\
\hspace{1em}Menos de 50 años & 124 & 41\%\\
\hspace{1em}\cellcolor{gray!10}{50 a 59 años} & \cellcolor{gray!10}{241} & \cellcolor{gray!10}{53\%}\\
\hspace{1em}60 años o más & 57 & 47\%\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Jerarquía}}\\
\hspace{1em}\cellcolor{gray!10}{Asistente} & \cellcolor{gray!10}{68} & \cellcolor{gray!10}{40\%}\\
\hspace{1em}Asociado & 270 & 53\%\\
\hspace{1em}\cellcolor{gray!10}{Titular} & \cellcolor{gray!10}{84} & \cellcolor{gray!10}{43\%}\\
\bottomrule
\end{tabular}
\endgroup{}

}

\end{table}%

\subsection{Idioma de la publicación}\label{idioma-de-la-publicaciuxf3n}

Se utiliza el idioma principal de la revista reportado por WoS, Scopus o
Scielo como \emph{proxy} para el idioma de la publicación. Dado que
algunas revistas permiten publicaciones en múltiples idiomas, éstas
fueron recodificadas como multidiomas. De tal forma se encontró
información para 927 publicaciones. Los datos apuntan a que el principal
idioma de publicación es el inglés, con 374 artículos, o el 45\% del
total. Le sigue el español, con 189 publicaciones que representan el
23\% del total. Fuera de estos dos idiomas, solo es relevante el
portugués, con un 4\% del total de artículos. Asimismo, existe una
amplía proporción (28\%) de publicaciones en revistas que permiten
escribir en más de un idioma, muy posiblemente incluyendo alguno de los
idiomas antes menconados. Finalmente, existe una cantidad cerca al 1\%
de escritos en otros idiomas, como el alemán, el francés y el italiano.

\begin{figure}

\caption{\label{fig-idioma}Distribución de publicaciones por idioma
según indexación (2020-2025)}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{03-resultados_files/figure-pdf/fig-idioma-1.pdf}}

}

\end{figure}%

En Figura~\ref{fig-idioma} se pueden apreciar las diferencias para cada
tipo de indexación. En Scielo, predominan ampliamente las publicaciones
en más de un idioma. Dado el carácter latinoamericano de esta base de
datos, es posible asumir que la mayoría de estos artículos fueron
escritos en español o, en menor medida, en portugués. El caso de Scopus
muestra mayor diversidad, coon el Español (32\%), las revistas
multidiomas (32\%) y el inglés (28\%) corresponden a tercios
prácticamente iguales. Finalmente, en WoS se observa un marcado
predominio del inglés (68\%) sobre otros idiomas.

\bookmarksetup{startatroot}

\chapter{Conclusiones}\label{sec-conclusiones}

El presente informe ofreció una caracterización sistemática de la
producción académica de la Facultad de Ciencias Sociales (FACSO) durante
el período 2020-2025. A partir de la consolidación de 1.162
publicaciones únicas y su análisis según distintas variables de
caracterización, es posible identificar un conjunto de fortalezas que
consolidan la posición de la Facultad, así como desafíos y oportunidades
que orientan la reflexión sobre futuras políticas de investigación.

\section{Fortalezas}\label{fortalezas-1}

La Facultad exhibe un volumen alto y sostenido de productividad
académica. Lejos de responder a un repunte coyuntural, la producción se
ha mantenido estable en los últimos años tras el incremento registrado
entre 2020 y 2021, lo que sugiere una capacidad instalada de
investigación y publicación robusta.

A este volumen se suma un nivel destacado de calidad e impacto. Una
proporción importante de la investigación de FACSO se publica en
revistas de prestigio ---mayoritariamente indexadas en Web of Science y
Scopus--- y una fracción relevante se ubica en los primeros cuartiles de
sus respectivas áreas de conocimiento. Este posicionamiento, junto con
el predominio de publicaciones con alcance internacional, refleja una
producción que no solo es alta en volumen, sino también visible y con
alcance internacional.

En consecuencia, la Facultad alberga un núcleo de investigadores
altamente productivos, cuyo elevado volumen de publicación se traduce
además en niveles de impacto sólidos, evidenciados en los indicadores de
citas y en el índice h institucional. Se trata de un capital académico
consolidado que constituye uno de los principales activos de la
Facultad.

Finalmente, cabe relevar la destacada productividad de las académicas de
la Facultad, que superan a sus pares masculinos en todos los indicadores
observados. Esto es consecuenten con los datos que muestran una mayor
capacidad para adjudicarse proyectos de investigación, incluso con menos
postulaciones, tanto a nivel nacional como de Facultad.

\section{Desafíos}\label{desafuxedos-1}

El principal desafío que emerge del análisis es la alta concentración de
la producción y del impacto en una minoría del cuerpo académico. Tanto
el volumen de publicaciones como las citas se distribuyen de manera
marcadamente desigual, lo que implica que una parte significativa del
cuerpo académico participa de forma más limitada en la producción
científica formal.

Esta concentración se expresa en brechas entre distintos grupos. En
particular, los profesores de jerarquía Asistente y los académicos de 60
años o más presentan cifras significativamente más bajas en la mayoría
de los indicadores. Estas diferencias pueden reflejar barreras para la
productividad académica tanto en las etapas iniciales de una trayectoria
académica como dinámicas propias de las fases más avanzadas de la
carrera.

A ello se añade una amplia heterogeneidad entre los departamentos de la
Facultad, tanto en volumen como en impacto. Con todo, esta diversidad
merece un análisis más profundo, pues es posible que esté reflejando
culturas disciplinares y lógicas de productividad propias de la
interdisciplinariedad que caracteriza a la Facultad.

\section{Oportunidades a futuro}\label{oportunidades-a-futuro-1}

En términos de políticas de investigación y publicación, los resultados
apuntan a la coexistencia de un núcleo altamente productivo con una
fuerte concentración y dispersión en la cantidad e impacto de las
publicaciones. Este diagnóstico abre la necesidad de diseñar políticas
focalizadas en determinados grupos de académicos con el objetivo de
fortalecer su productividad y reducir la dispersión observada,
aprovechando además el potencial de mentoría que representa el núcleo
consolidado.

En términos de gestión de la información, la consolidación de datos de
publicaciones realizada en este estudio constituye en sí misma un
resultado valioso. Por una parte, sienta las bases para la elaboración
de reportes periódicos que permitan monitorear la evolución de estos
indicadores en el tiempo. Por otra, habilita el desarrollo de análisis
más complejos, como modelos que expliquen las diferencias en
productividad entre grupos, o la aplicación de técnicas de procesamiento
de lenguaje natural para identificar los temas recurrentes en la
producción de la Facultad. De este modo, el trabajo aquí presentado no
se agota en un diagnóstico puntual, sino que abre una agenda de
seguimiento y profundización analítica.

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-moya_publicaciones_}
Moya, C. (2022). \emph{{Publicaciones académicas y académicos FACSO}}.

\end{CSLReferences}


\backmatter

% --- Cuerpo del libro (capítulos) en arábigos ---
\mainmatter
\pagestyle{scrheadings}

% --- (Opcional) Estilo del índice general ---
% \addtocontents{toc}{\protect\thispagestyle{plain}}


\end{document}
